# Generated by Django 5.2.8 on 2026-03-07 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='URL-ൽ കാണിക്കാൻ (ഉദാ: /mens-collection)', unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('hex_code', models.CharField(blank=True, help_text='കളർ കോഡ് (ഉദാ: #000000)', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, help_text='ഓഫർ വില ഉണ്ടെങ്കിൽ മാത്രം നൽകുക', max_digits=10, null=True)),
                ('stock', models.PositiveIntegerField(default=0, help_text='സ്റ്റോക്കിൽ എത്ര എണ്ണം ഉണ്ട്?')),
                ('sku', models.CharField(help_text='സ്റ്റോക്ക് കീപ്പിംഗ് യൂണിറ്റ് (ഉദാ: LUX-TSHIRT-001)', max_length=50, unique=True)),
                ('main_image', models.ImageField(upload_to='product_images/main/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_trending', models.BooleanField(default=False, help_text="ഹോം പേജിൽ 'Trending Now' സെക്ഷനിൽ കാണിക്കാൻ")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
                ('colors', models.ManyToManyField(blank=True, to='products.color')),
                ('sizes', models.ManyToManyField(blank=True, to='products.size')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/gallery/')),
                ('alt_text', models.CharField(blank=True, help_text='ഇമേജ് ലോഡ് ആയില്ലെങ്കിൽ കാണിക്കേണ്ട ടെക്സ്റ്റ്', max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='products.product')),
            ],
        ),
    ]
