# Generated by Django 5.2.8 on 2026-03-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productgallery_reviewrating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manual_avg_rating',
            field=models.FloatField(default=0.0, help_text='ഉദാഹരണത്തിന് 4.8 എന്ന് നൽകുക'),
        ),
        migrations.AddField(
            model_name='product',
            name='manual_review_count',
            field=models.IntegerField(default=0, help_text='ഉദാഹരണത്തിന് 155 എന്ന് നൽകിയാൽ 155 റിവ്യൂസ് എന്ന് കാണിക്കും'),
        ),
    ]
