# Generated by Django 5.2.12 on 2026-03-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='stock_l',
            field=models.IntegerField(default=0, verbose_name='Large (L) Stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_m',
            field=models.IntegerField(default=0, verbose_name='Medium (M) Stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_s',
            field=models.IntegerField(default=0, verbose_name='Small (S) Stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_xl',
            field=models.IntegerField(default=0, verbose_name='Extra Large (XL) Stock'),
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
