# Generated by Django 5.2.12 on 2026-03-10 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_sizes_remove_product_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_l',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_m',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_s',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_xl',
        ),
        migrations.AddField(
            model_name='productgallery',
            name='color',
            field=models.ForeignKey(blank=True, help_text='ഈ ഫോട്ടോ ഏത് കളർ ഷർട്ടിന്റേതാണെന്ന് സെലക്ട് ചെയ്യുക', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manual_avg_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='product',
            name='manual_review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.size')),
            ],
            options={
                'unique_together': {('product', 'color', 'size')},
            },
        ),
    ]
