# Generated by Django 5.2.12 on 2026-03-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_size_remove_product_colors_remove_product_stock_l_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='store/variant_images/'),
        ),
    ]
